version: '3.6'

services:
  'react-app':
    build:
      context: './'
    image: 'sample:react-app'
    ports:
      - 3000:3000
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
